# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liuxue_leixing', models.CharField(max_length=50)),
                ('zhongwen', models.CharField(max_length=200)),
                ('jiangxuejin', models.IntegerField(blank=True, null=True)),
                ('zhuanye', models.CharField(max_length=100)),
                ('chengshi', models.CharField(blank=True, max_length=50, null=True)),
                ('xuexiaoleibie', models.CharField(max_length=50)),
                ('xueli', models.CharField(max_length=50)),
                ('xueli_leibie', models.CharField(max_length=50)),
                ('jigou', models.CharField(max_length=50)),
                ('jigou_city', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('offer_huoqu', models.CharField(blank=True, max_length=20, null=True)),
                ('xuezhi', models.IntegerField(blank=True, null=True)),
                ('xuexiao', models.CharField(blank=True, max_length=50, null=True)),
                ('xueli_chengdu', models.CharField(blank=True, max_length=50, null=True)),
                ('gaokao', models.CharField(blank=True, max_length=20, null=True)),
                ('ielts', models.FloatField(blank=True, null=True)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('tofel', models.IntegerField(blank=True, null=True)),
                ('act', models.IntegerField(blank=True, null=True)),
                ('tiaojian', models.CharField(blank=True, max_length=50, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'benke',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shuoshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liuxue_leixing', models.CharField(max_length=50)),
                ('zhongwen', models.CharField(max_length=200)),
                ('jiangxuejin', models.IntegerField(blank=True, null=True)),
                ('zhuanye', models.CharField(max_length=100)),
                ('chengshi', models.CharField(blank=True, max_length=50, null=True)),
                ('xuexiaoleibie', models.CharField(max_length=50)),
                ('xueli', models.CharField(max_length=50)),
                ('xueli_leibie', models.CharField(max_length=50)),
                ('zhuanye_ch', models.CharField(max_length=100)),
                ('jigou', models.CharField(max_length=50)),
                ('jigou_city', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('offer_huoqu', models.CharField(blank=True, max_length=20, null=True)),
                ('xuezhi', models.IntegerField(blank=True, null=True)),
                ('xuexiao', models.CharField(blank=True, max_length=50, null=True)),
                ('xueli_chengdu', models.CharField(blank=True, max_length=50, null=True)),
                ('ielts', models.FloatField(blank=True, null=True)),
                ('tofel', models.IntegerField(blank=True, null=True)),
                ('gre', models.IntegerField(blank=True, null=True)),
                ('gmat', models.IntegerField(blank=True, null=True)),
                ('tiaojian', models.CharField(blank=True, max_length=50, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shuoshi',
                'managed': False,
            },
        ),
    ]
