# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benke',
            options={'managed': False, 'verbose_name': '本科Offer', 'verbose_name_plural': '本科Offers'},
        ),
    ]
